export const talks = [
  {
    year: "2021",
    talks: [
      {
        title: "Testing Web Accessibility",
        conference: "JSDay Spain",
        date: "TBD 2021",
        location: "Madrid, Spain",
        link: "http://jsday.es/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
    ],
  },
  {
    year: "2020",
    talks: [
      {
        title: "How does your website 'sound' like?",
        conference: "DevFest Siberia",
        date: "12/01/2020",
        location: "Novosibirsk, Russia [Online]",
        link: "https://gdg-siberia.com/",
        video: "",
        slides:
          "https://speakerdeck.com/bolonio/how-does-your-website-sound-like",
      },
      {
        title: "Testing Web Accessibility",
        conference: "Intersection conference",
        date: "10/01/2020",
        location: "Milano, Italy [Online]",
        link: "https://www.intersection-conference.eu/",
        video: "https://www.youtube.com/watch?v=Zc5T_Y2ueKY",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Accessibility in Web Development",
        conference: "UpLeveled (Workshop)",
        date: "10/01/2020",
        location: "Vienna, Austria",
        link: "https://upleveled.io/",
        video: "",
        slides:
          "https://speakerdeck.com/bolonio/accessibility-in-web-development",
      },
      {
        title: "Testing Web Accessibility",
        conference: "Frontend Love Meetup",
        date: "08/01/2020",
        location: "YouTube [Online]",
        link: "http://frontenddeveloperlove.com/",
        video: "https://www.youtube.com/watch?v=XDncZ-UZ8Hw",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "BarcelonaJS",
        date: "07/01/2020",
        location: "Barcelona, Spain [Online]",
        link: "https://www.meetup.com/BarcelonaJS/",
        video: "https://www.youtube.com/watch?v=sc1CfX2-8v0",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "DevTalks Reimagined",
        date: "06/01/2020",
        location: "Bucharest, Romania [Online]",
        link: "https://www.devtalks.ro/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "UXDX Community Eastern Europe",
        date: "06/01/2020",
        location: "Vienna, Austria [Online]",
        link: "https://uxdx.com/community/easterneurope/2020",
        video: "https://www.youtube.com/watch?v=-dBsgG7L2EQ",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Accessibility in Web Development",
        conference: "UpLeveled (Workshop)",
        date: "06/01/2020",
        location: "Vienna, Austria",
        link: "https://upleveled.io/",
        video: "",
        slides:
          "https://speakerdeck.com/bolonio/accessibility-in-web-development",
      },
      {
        title: "Testing Web Accessibility",
        conference: "Reactadelphia",
        date: "04/01/2020",
        location: "Philadelphia, USA [Online]",
        link: "https://twitter.com/reactadelphia",
        video: "https://www.youtube.com/watch?v=Ocem7jAb-Ik",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "StayAtHome Conf",
        date: "03/01/2020",
        location: "Home [Online]",
        link: "https://www.stayathomeconf.com/",
        video: "https://www.youtube.com/watch?v=XmSK1t0w1L8",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "FrontConf",
        date: "03/01/2020",
        location: "Munich, Germany [Online]",
        link: "https://frontconf.com/",
        video: "https://www.youtube.com/watch?v=xCGS1Vq777c",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "A11yClub Berlin",
        date: "03/01/2020",
        location: "Berlin, Germany [Online]",
        link: "https://a11y-meetup-berlin.de/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Accessibility in Web Development",
        conference: "UpLeveled (Workshop)",
        date: "03/01/2020",
        location: "Vienna, Austria",
        link: "https://upleveled.io/",
        video: "",
        slides:
          "https://speakerdeck.com/bolonio/accessibility-in-web-development",
      },
      {
        title: "Testing Web Accessibility",
        conference: "ViennaJS",
        date: "02/01/2020",
        location: "Vienna, Austria",
        link: "https://viennajs.org/en/meetup/2020-02",
        video: "https://www.youtube.com/watch?v=ZupKHcb9w-k",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "TestBustersNight Vienna",
        date: "01/01/2020",
        location: "Vienna, Austria",
        link: "https://www.meetup.com/Agile-Test-Automation-Meetup-VIENNA",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Diversity Pannel",
        conference: "SQLSaturday (Diversity Pannel)",
        date: "01/01/2020",
        location: "Vienna, Austria",
        link: "https://www.sqlsaturday.com/917/EventHome.aspx",
        video: "",
        slides: "",
      },
    ],
  },
  {
    year: "2019",
    talks: [
      {
        title: "Testing Web Accessibility",
        conference: "Heisenbug Conf",
        date: "12/01/2019",
        location: "Moscow, Russia",
        link: "https://heisenbug-moscow.ru/en/",
        video: "https://www.youtube.com/watch?v=GyXkH5ZmSfk",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "DevFest Siberia",
        date: "12/01/2019",
        location: "Novosibirsk, Russia",
        link: "https://gdg-siberia.com/",
        video: "https://www.youtube.com/watch?v=1eDCdL-3uI0",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "Developer Melange",
        date: "12/01/2019",
        location: "Podcast",
        link: "https://developermelange.github.io/",
        video: "http://developermelange.com/025-accessibility-101/",
        slides: "",
      },
      {
        title: "Testing Web Accessibility",
        conference: "WebClerks",
        date: "11/01/2019",
        location: "Vienna, Austria",
        link: "https://webclerks.at/",
        video: "https://youtu.be/ucLEMETfrTA?t=14220",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "DevFest Vienna",
        date: "11/01/2019",
        location: "Vienna, Austria",
        link: "https://devfest.at/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "React Vienna",
        date: "11/01/2019",
        location: "Vienna, Austria",
        link: "https://twitter.com/reactvienna",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "JSConf Colombia",
        date: "10/01/2019",
        location: "Medellín, Colombia",
        link: "http://jsconf.co/",
        video: "",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
      {
        title: "Testing Web Accessibility",
        conference: "AXSChat",
        date: "10/01/2019",
        location: "YouTube",
        link: "http://axschat.com/",
        video: "https://www.youtube.com/watch?v=JFaS1JGO71w",
        slides: "",
      },
      {
        title: "Testing Web Accessibility",
        conference: "UpLeveled (Workshop)",
        date: "10/01/2019",
        location: "Vienna, Austria",
        link: "https://upleveled.io/",
        video: "",
        slides:
          "https://speakerdeck.com/bolonio/accessibility-in-web-development",
      },
      {
        title: "Testing Web Accessibility",
        conference: "Accessibility talks",
        date: "08/01/2019",
        location: "YouTube",
        link: "https://www.youtube.com/c/accessibilitytalks",
        video: "https://www.youtube.com/watch?v=Nq6UhL_QvZk",
        slides: "https://speakerdeck.com/bolonio/testing-web-accessibility",
      },
    ],
  },
  {
    year: "2018",
    talks: [
      {
        title: "How does your website 'sound' like?",
        conference: "UX Vienna",
        date: "12/01/2018",
        location: "Vienna, Austria",
        link: "https://uxvienna.at/",
        video: "",
        slides:
          "https://speakerdeck.com/bolonio/how-does-your-website-sound-like",
      },
      {
        title: "How does your website 'sound' like?",
        conference: "DevFest Vienna",
        date: "11/01/2018",
        location: "Vienna, Austria",
        link: "https://devfest.at/",
        video: "https://www.youtube.com/watch?v=yKYA-7tczuk",
        slides:
          "https://speakerdeck.com/bolonio/how-does-your-website-sound-like",
      },
      {
        title: "Willhaben Markup Language WHML",
        conference: "ViennaJS",
        date: "05/01/2018",
        location: "Vienna, Austria",
        link: "https://viennajs.org/",
        video: "https://www.youtube.com/watch?v=tJXzyHHh4pc",
        slides:
          "https://speakerdeck.com/bolonio/willhaben-markup-language-whml",
      },
    ],
  },
  {
    year: "2017",
    talks: [
      {
        title: "Dark Patterns - User Interfaces Designed to Trick People",
        conference: "UX Vienna",
        date: "11/01/2017",
        location: "Vienna, Austria",
        link: "https://uxvienna.at/",
        video: "",
        slides: "http://slides.com/adrianbolonio/darkpatterns-uxvienna#/",
      },
    ],
  },
]
